var data = [
"Chicago, IL",
"Ann Arbor, MI",
"Bloomfield Hills, MI",
"Detroit, MI",
"Detroit, MI",
"Grosse Pointe, MI",
"Oak Park, MI",
"West Bloomfield, MI",
"Clinton Township, MI",
"Troy, MI",
"Detroit, MI",
"Novi, MI",
"Royal Oak, MI",
"Monroe, MI",
"Birmingham, MI",
"Franklin, MI",
"Southfield, MI",
"Okemos, MI",
"Detroit, MI",
"Detroit, MI",
"Sterling Heights, MI",
"Warren, MI",
"Ann Arbor, MI",
"Ann Arbor, MI",
"Hamtramck, MI",
"Royal Oak, MI",
"Ann Arbor, MI",
"Royal Oak, MI",
"Canton, MI",
"Ann Arb, MI",
"Rochester, MI",
"Royal Oak, MI",
"Ypsilanti, MI",
"Farmington, MI",
"Detroit, MI",
"Ann Arbor, MI",
"Detroit, MI",
"Southfield, MI",
"Livonia, MI",
"Brighton, MI",
"South Rockwood, MI",
"Royal Oak, MI",
"Ann Arbor, MI",
"Detroit, MI",
"Ann Arbor, MI",
"Dryden, MI",
"Detroit, MI",
"Detroit, MI",
"Ann Arbor, MI",
"Ann Arbor, MI"
];