# This is an attempt to use the workflow
# We will take a csv from meetup and convert it into a json of lat, lon points
# with the number of occurences
---
input_name: data/sp500.html


tasks:
# create some data to analyze.
  -
    creates: data/city_names.json
    command:
      - mkdir -p $(dirname {{creates}})
      - python code/extract_city_names.py {{creates}}
  -
    creates: data/list_of_clusters.json
    depends: data/city_names.json
    command:
      - mkdir -p $(dirname {{creates}})
      - python code/kmeans.py {{depends}} {{creates}}
  -
    creates: data/json/
    depends: 
      - data/city_names.json
      - data/list_of_clusters.json
    command:
      - mkdir -p {{creates}}
      - python code/geo_median.py {{depends|join(' ')}} {{creates}}
  -
    creates: js/data.js
    depends: 
      - data/city_names.json
      - data/json/
    command:
      - mkdir -p $(dirname {{creates}})
      - python code/make_data.py {{depends|join(' ')}} {{creates}}