# This is an attempt to use the workflow
# We will take a csv from meetup and convert it into a json of lat, lon points
# with the number of occurences
---
input_name: data/sp500.html


tasks:
# create some data to analyze.
  -
    creates: data/city_names.json
    command:
      - mkdir -p $(dirname {{creates}})
      - python code/extract_city_names.py {{creates}}
  -
    creates: data/data.js
    depends: data/city_names.json
    command:
      - mkdir -p $(dirname {{creates}})
      - python code/make_data.py {{depends}} {{creates}}